name: main

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 5"

jobs:

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: kzenv-test
        run: echo GITHUB_API_TOKEN && make test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
